sonar.projectKey=zakat-backend
sonar.projectName=Zakat Backend

sonar.sources=src

sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://host.docker.internal:9000